version: 2
jobs:
  build:
    docker:
      # - image: python:3.6
      - image: kikagaku/pytest
    steps:
      - checkout
      # - run:
      #     name: install dependencies
      #     command: |
      #       pip install pytest
      #       # pip install pytest-ipynb
      #       pip install pytest-cov
      #       pip install numpy pandas matplotlib
      #       pip install chainer
      - run:
          name: remove all python scripts
          command: |
            echo `ls`
            array=`find *.py`
            echo $array
            for a in $array; do
              rm $a
            done
      - run:
          name: convert ipynb to py
          command: |
            array=`find *.ipynb`
            for a in $array; do
              jupyter nbconvert --to script $a
            done
      - run:
          name: run test
          command: |
            # echo hello
            pytest -v
            # pytest --junitxml=test-reports/junit.xml
      # - store-test-results:
      #     path: test-reports
      # - run:
      #     name: run test-cov
      #     command: |
      #       . venv/bin/activate
      #       pytest --cov=src
