version: 2
jobs:
  build:
    docker:
      - image: kikagaku/pytest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            # sudo pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            python generate_test.py
            pytest -v --timeout=300 > result.log
            python update_files.py

     - run:
          name: Build Success
          when: on_success
          command: |
            if [ "$CIRCLE_NODE_INDEX" == 0 ]; then
              deploy.sh
            fi
